openapi: 3.0.3
info:
  title: DietiEstates25 Search Service
  version: 1.0.0
  description: Motore di ricerca avanzata e gestione storico ricerche

servers:
  - url: http://localhost:3003
    description: Development server

paths:
  /search:
    post:
      operationId: searchProperties
      summary: Ricerca proprietà con filtri avanzati
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/SearchFilters'
                - type: object
                  properties:
                    page:
                      type: integer
                      default: 1
                      minimum: 1
                    limit:
                      type: integer
                      default: 20
                      minimum: 1
                      maximum: 100
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        '400':
          description: Invalid search parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /search/suggestions:
    get:
      operationId: getSearchSuggestions
      summary: Suggerimenti di ricerca
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            minLength: 2
        - name: type
          in: query
          schema:
            type: string
            enum: [location, property_type, feature]
            default: location
      responses:
        '200':
          description: Search suggestions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /search/saved:
    get:
      operationId: getSavedSearches
      summary: Ottieni ricerche salvate
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Saved searches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SavedSearch'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      operationId: saveSearch
      summary: Salva ricerca
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - filters
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                filters:
                  $ref: '#/components/schemas/SearchFilters'
                isNotificationEnabled:
                  type: boolean
                  default: true
      responses:
        '201':
          description: Search saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedSearch'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /search/saved/{searchId}:
    put:
      operationId: updateSavedSearch
      summary: Aggiorna ricerca salvata
      security:
        - bearerAuth: []
      parameters:
        - name: searchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SavedSearchUpdate'
      responses:
        '200':
          description: Saved search updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedSearch'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Saved search not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      operationId: deleteSavedSearch
      summary: Elimina ricerca salvata
      security:
        - bearerAuth: []
      parameters:
        - name: searchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Saved search deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Saved search not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /search/history:
    get:
      operationId: getSearchHistory
      summary: Ottieni storico ricerche (Req. 10)
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Search history
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchHistory'
                  totalCount:
                    type: integer
                    minimum: 0
                  currentPage:
                    type: integer
                    minimum: 1
                  totalPages:
                    type: integer
                    minimum: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SearchFilters:
      type: object
      properties:
        location:
          type: string
          description: "City or area name"
        propertyType:
          type: string
          enum: [apartment, villa, house, loft, office, commercial, land]
        listingType:
          type: string
          enum: [sale, rent]
        priceMin:
          type: number
          format: float
          minimum: 0
        priceMax:
          type: number
          format: float
          minimum: 0
        bedrooms:
          type: integer
          minimum: 0
          maximum: 20
        bathrooms:
          type: integer
          minimum: 0
          maximum: 20
        areaMin:
          type: number
          format: float
          minimum: 0
        areaMax:
          type: number
          format: float
          minimum: 0
        energyClass:
          type: string
          enum: [A+, A, B, C, D, E, F, G]
        hasElevator:
          type: boolean
        hasBalcony:
          type: boolean
        hasGarden:
          type: boolean
        hasParking:
          type: boolean
        radius:
          type: number
          format: float
          minimum: 0.1
          maximum: 100
          default: 10
          description: "Search radius in kilometers"
        centerLat:
          type: number
          format: float
          minimum: -90
          maximum: 90
          description: "Center latitude for radius search"
        centerLng:
          type: number
          format: float
          minimum: -180
          maximum: 180
          description: "Center longitude for radius search"
        features:
          type: array
          items:
            type: string
          description: "Required features"
        sortBy:
          type: string
          enum: [price_asc, price_desc, area_asc, area_desc, date_desc, relevance]
          default: relevance

    SearchResult:
      type: object
      properties:
        properties:
          type: array
          items:
            $ref: '#/components/schemas/Property'
        totalCount:
          type: integer
          minimum: 0
        currentPage:
          type: integer
          minimum: 1
        totalPages:
          type: integer
          minimum: 0
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean
        searchTime:
          type: number
          format: float
          description: "Search execution time in milliseconds"
        appliedFilters:
          $ref: '#/components/schemas/SearchFilters'

    SavedSearch:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        filters:
          $ref: '#/components/schemas/SearchFilters'
        isNotificationEnabled:
          type: boolean
          default: true
        lastResultCount:
          type: integer
          minimum: 0
        hasNewResults:
          type: boolean
          default: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    SavedSearchUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        filters:
          $ref: '#/components/schemas/SearchFilters'
        isNotificationEnabled:
          type: boolean

    SearchHistory:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        filters:
          $ref: '#/components/schemas/SearchFilters'
        resultCount:
          type: integer
          minimum: 0
        searchedAt:
          type: string
          format: date-time
        source:
          type: string
          enum: [web, mobile, api]
          default: web
        executionTime:
          type: number
          format: float
          description: "Search execution time in milliseconds"

    Property:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        propertyType:
          type: string
          enum: [apartment, villa, house, loft, office, commercial, land]
        listingType:
          type: string
          enum: [sale, rent]
        status:
          type: string
          enum: [active, pending, sold, rented, withdrawn]
        bedrooms:
          type: integer
        bathrooms:
          type: integer
        area:
          type: number
          format: float
        floor:
          type: string
        energyClass:
          type: string
          enum: [A+, A, B, C, D, E, F, G]
        hasElevator:
          type: boolean
        hasBalcony:
          type: boolean
        hasGarden:
          type: boolean
        hasParking:
          type: boolean
        features:
          type: array
          items:
            type: string
        address:
          $ref: '#/components/schemas/PropertyAddress'
        location:
          $ref: '#/components/schemas/PropertyLocation'
        images:
          type: array
          items:
            $ref: '#/components/schemas/PropertyImage'
        agentId:
          type: string
          format: uuid
        agent:
          $ref: '#/components/schemas/Agent'
        views:
          type: integer
        favorites:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        relevanceScore:
          type: number
          format: float
          description: "Search relevance score (0-1)"

    PropertyAddress:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        province:
          type: string
        zipCode:
          type: string
        country:
          type: string

    PropertyLocation:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float

    PropertyImage:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        alt:
          type: string
        isPrimary:
          type: boolean
        order:
          type: integer

    Agent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        agencyName:
          type: string
        rating:
          type: number
          format: float
        avatar:
          type: string
          format: uri

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
