openapi: 3.0.3
info:
  title: DietiEstates25 Property Service
  version: 1.0.0
  description: Gestione proprietà immobiliari

servers:
  - url: http://localhost:3002
    description: Development server

paths:
  /properties:
    get:
      operationId: getProperties
      summary: Lista proprietà con paginazione
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: agentId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Properties list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'

    post:
      operationId: createProperty
      summary: Crea nuova proprietà
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyCreateRequest'
      responses:
        '201':
          description: Property created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /properties/{propertyId}:
    get:
      operationId: getPropertyById
      summary: Ottieni dettagli proprietà
      parameters:
        - name: propertyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Property details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      operationId: updateProperty
      summary: Aggiorna proprietà
      security:
        - bearerAuth: []
      parameters:
        - name: propertyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyUpdateRequest'
      responses:
        '200':
          description: Property updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      operationId: deleteProperty
      summary: Elimina proprietà
      security:
        - bearerAuth: []
      parameters:
        - name: propertyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Property deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /properties/{propertyId}/view:
    post:
      operationId: recordPropertyView
      summary: Registra visualizzazione proprietà
      parameters:
        - name: propertyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  type: string
                  default: "web"
                  enum: [web, mobile, direct, search]
      responses:
        '200':
          description: View recorded
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /properties/{propertyId}/images:
    post:
      operationId: uploadPropertyImages
      summary: Upload immagini proprietà
      security:
        - bearerAuth: []
      parameters:
        - name: propertyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  maxItems: 20
      responses:
        '200':
          description: Images uploaded
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PropertyImage'
        '400':
          description: Invalid files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Property:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
          minimum: 0
        propertyType:
          type: string
          enum: [apartment, villa, house, loft, office, commercial, land]
        listingType:
          type: string
          enum: [sale, rent]
        status:
          type: string
          enum: [active, pending, sold, rented, withdrawn]
          default: active
        bedrooms:
          type: integer
          minimum: 0
        bathrooms:
          type: integer
          minimum: 0
        area:
          type: number
          format: float
          minimum: 0
        floor:
          type: string
        energyClass:
          type: string
          enum: [A+, A, B, C, D, E, F, G]
        hasElevator:
          type: boolean
          default: false
        hasBalcony:
          type: boolean
          default: false
        hasGarden:
          type: boolean
          default: false
        hasParking:
          type: boolean
          default: false
        features:
          type: array
          items:
            type: string
        address:
          $ref: '#/components/schemas/PropertyAddress'
        location:
          $ref: '#/components/schemas/PropertyLocation'
        images:
          type: array
          items:
            $ref: '#/components/schemas/PropertyImage'
        agentId:
          type: string
          format: uuid
        agent:
          $ref: '#/components/schemas/Agent'
        isActive:
          type: boolean
          default: true
        views:
          type: integer
          minimum: 0
          default: 0
        favorites:
          type: integer
          minimum: 0
          default: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PropertyCreateRequest:
      type: object
      required:
        - title
        - description
        - price
        - propertyType
        - listingType
        - bedrooms
        - bathrooms
        - area
        - address
        - location
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 200
        description:
          type: string
          minLength: 50
          maxLength: 2000
        price:
          type: number
          format: float
          minimum: 0
        propertyType:
          type: string
          enum: [apartment, villa, house, loft, office, commercial, land]
        listingType:
          type: string
          enum: [sale, rent]
        bedrooms:
          type: integer
          minimum: 0
          maximum: 20
        bathrooms:
          type: integer
          minimum: 0
          maximum: 20
        area:
          type: number
          format: float
          minimum: 1
          maximum: 10000
        floor:
          type: string
        energyClass:
          type: string
          enum: [A+, A, B, C, D, E, F, G]
        hasElevator:
          type: boolean
          default: false
        hasBalcony:
          type: boolean
          default: false
        hasGarden:
          type: boolean
          default: false
        hasParking:
          type: boolean
          default: false
        features:
          type: array
          items:
            type: string
          maxItems: 20
        address:
          $ref: '#/components/schemas/PropertyAddress'
        location:
          $ref: '#/components/schemas/PropertyLocation'

    PropertyUpdateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 200
        description:
          type: string
          minLength: 50
          maxLength: 2000
        price:
          type: number
          format: float
          minimum: 0
        status:
          type: string
          enum: [active, pending, sold, rented, withdrawn]
        bedrooms:
          type: integer
          minimum: 0
          maximum: 20
        bathrooms:
          type: integer
          minimum: 0
          maximum: 20
        area:
          type: number
          format: float
          minimum: 1
          maximum: 10000
        floor:
          type: string
        energyClass:
          type: string
          enum: [A+, A, B, C, D, E, F, G]
        hasElevator:
          type: boolean
        hasBalcony:
          type: boolean
        hasGarden:
          type: boolean
        hasParking:
          type: boolean
        features:
          type: array
          items:
            type: string
          maxItems: 20
        address:
          $ref: '#/components/schemas/PropertyAddress'
        isActive:
          type: boolean

    PropertyAddress:
      type: object
      required:
        - street
        - city
        - province
        - zipCode
        - country
      properties:
        street:
          type: string
          minLength: 5
          maxLength: 200
        city:
          type: string
          minLength: 2
          maxLength: 100
        province:
          type: string
          minLength: 2
          maxLength: 100
        zipCode:
          type: string
          pattern: '^\d{5}$'
        country:
          type: string
          default: "Italy"

    PropertyLocation:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: float
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: float
          minimum: -180
          maximum: 180

    PropertyImage:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        alt:
          type: string
        isPrimary:
          type: boolean
          default: false
        order:
          type: integer
          minimum: 0

    Agent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        avatar:
          type: string
          format: uri
        agencyName:
          type: string
        licenseNumber:
          type: string
        rating:
          type: number
          format: float
          minimum: 0
          maximum: 5
        reviewsCount:
          type: integer
          minimum: 0

    SearchResult:
      type: object
      properties:
        properties:
          type: array
          items:
            $ref: '#/components/schemas/Property'
        totalCount:
          type: integer
          minimum: 0
        currentPage:
          type: integer
          minimum: 1
        totalPages:
          type: integer
          minimum: 0
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
